=== jonathan-hunter/jonathan-hunter.github.io/assets/json/resume-schema.json
{"$schema":"http://json-schema.org/draft-07/schema#","$id":"http://example.com/example.json","additionalProperties":true,"definitions":{"iso8601":{"type":"string","description":"Similar to the standard date type, but each section after the year is optional. e.g. 2014-06-29 or 2023-04","pattern":"^([1-2][0-9]{3}-[0-1][0-9]-[0-3][0-9]|[1-2][0-9]{3}-[0-1][0-9]|[1-2][0-9]{3})$"}},"properties":{"$schema":{"type":"string","description":"link to the version of the schema that can validate the resume","format":"uri"},"basics":{"type":"object","additionalProperties":true,"properties":{"name":{"type":"string"},"label":{"type":"string","description":"e.g. Web Developer"},"image":{"type":"string","description":"URL (as per RFC 3986) to a image in JPEG or PNG format"},"email":{"type":"string","description":"e.g. thomas@gmail.com","format":"email"},"phone":{"type":"string","description":"Phone numbers are stored as strings so use any format you like, e.g. 712-117-2923"},"url":{"type":"string","description":"URL (as per RFC 3986) to your website, e.g. personal homepage","format":"uri"},"summary":{"type":"string","description":"Write a short 2-3 sentence biography about yourself"},"location":{"type":"object","additionalProperties":true,"properties":{"address":{"type":"string","description":"To add multiple address lines, use \n. For example, 1234 Glücklichkeit Straße\nHinterhaus 5. Etage li."},"postalCode":{"type":"string"},"city":{"type":"string"},"countryCode":{"type":"string","description":"code as per ISO-3166-1 ALPHA-2, e.g. US, AU, IN"},"region":{"type":"string","description":"The general region where you live. Can be a US state, or a province, for instance."}}},"profiles":{"type":"array","description":"Specify any number of social networks that you participate in","additionalItems":false,"items":{"type":"object","additionalProperties":true,"properties":{"network":{"type":"string","description":"e.g. Facebook or Twitter"},"username":{"type":"string","description":"e.g. neutralthoughts"},"url":{"type":"string","description":"e.g. http://twitter.example.com/neutralthoughts","format":"uri"}}}}}},"work":{"type":"array","additionalItems":false,"items":{"type":"object","additionalProperties":true,"properties":{"name":{"type":"string","description":"e.g. Facebook"},"location":{"type":"string","description":"e.g. Menlo Park, CA"},"description":{"type":"string","description":"e.g. Social Media Company"},"position":{"type":"string","description":"e.g. Software Engineer"},"url":{"type":"string","description":"e.g. http://facebook.example.com","format":"uri"},"startDate":{"$ref":"#/definitions/iso8601"},"endDate":{"$ref":"#/definitions/iso8601"},"summary":{"type":"string","description":"Give an overview of your responsibilities at the company"},"highlights":{"type":"array","description":"Specify multiple accomplishments","additionalItems":false,"items":{"type":"string","description":"e.g. Increased profits by 20% from 2011-2012 through viral advertising"}}}}},"volunteer":{"type":"array","additionalItems":false,"items":{"type":"object","additionalProperties":true,"properties":{"organization":{"type":"string","description":"e.g. Facebook"},"position":{"type":"string","description":"e.g. Software Engineer"},"url":{"type":"string","description":"e.g. http://facebook.example.com","format":"uri"},"startDate":{"$ref":"#/definitions/iso8601"},"endDate":{"$ref":"#/definitions/iso8601"},"summary":{"type":"string","description":"Give an overview of your responsibilities at the company"},"highlights":{"type":"array","description":"Specify accomplishments and achievements","additionalItems":false,"items":{"type":"string","description":"e.g. Increased profits by 20% from 2011-2012 through viral advertising"}}}}},"education":{"type":"array","additionalItems":false,"items":{"type":"object","additionalProperties":true,"properties":{"institution":{"type":"string","description":"e.g. Massachusetts Institute of Technology"},"url":{"type":"string","description":"e.g. http://facebook.example.com","format":"uri"},"area":{"type":"string","description":"e.g. Arts"},"studyType":{"type":"string","description":"e.g. Bachelor"},"startDate":{"$ref":"#/definitions/iso8601"},"endDate":{"$ref":"#/definitions/iso8601"},"score":{"type":"string","description":"grade point average, e.g. 3.67/4.0"},"courses":{"type":"array","description":"List notable courses/subjects","additionalItems":false,"items":{"type":"string","description":"e.g. H1302 - Introduction to American history"}}}}},"awards":{"type":"array","description":"Specify any awards you have received throughout your professional career","additionalItems":false,"items":{"type":"object","additionalProperties":true,"properties":{"title":{"type":"string","description":"e.g. One of the 100 greatest minds of the century"},"date":{"$ref":"#/definitions/iso8601"},"awarder":{"type":"string","description":"e.g. Time Magazine"},"summary":{"type":"string","description":"e.g. Received for my work with Quantum Physics"}}}},"certificates":{"type":"array","description":"Specify any certificates you have received throughout your professional career","additionalItems":false,"items":{"type":"object","additionalProperties":true,"properties":{"name":{"type":"string","description":"e.g. Certified Kubernetes Administrator"},"date":{"$ref":"#/definitions/iso8601"},"url":{"type":"string","description":"e.g. http://example.com","format":"uri"},"issuer":{"type":"string","description":"e.g. CNCF"}}}},"publications":{"type":"array","description":"Specify your publications through your career","additionalItems":false,"items":{"type":"object","additionalProperties":true,"properties":{"name":{"type":"string","description":"e.g. The World Wide Web"},"publisher":{"type":"string","description":"e.g. IEEE, Computer Magazine"},"releaseDate":{"$ref":"#/definitions/iso8601"},"url":{"type":"string","description":"e.g. http://www.computer.org.example.com/csdl/mags/co/1996/10/rx069-abs.html","format":"uri"},"summary":{"type":"string","description":"Short summary of publication. e.g. Discussion of the World Wide Web, HTTP, HTML."}}}},"skills":{"type":"array","description":"List out your professional skill-set","additionalItems":false,"items":{"type":"object","additionalProperties":true,"properties":{"name":{"type":"string","description":"e.g. Web Development"},"level":{"type":"string","description":"e.g. Master"},"keywords":{"type":"array","description":"List some keywords pertaining to this skill","additionalItems":false,"items":{"type":"string","description":"e.g. HTML"}}}}},"languages":{"type":"array","description":"List any other languages you speak","additionalItems":false,"items":{"type":"object","additionalProperties":true,"properties":{"language":{"type":"string","description":"e.g. English, Spanish"},"fluency":{"type":"string","description":"e.g. Fluent, Beginner"}}}},"interests":{"type":"array","additionalItems":false,"items":{"type":"object","additionalProperties":true,"properties":{"name":{"type":"string","description":"e.g. Philosophy"},"keywords":{"type":"array","additionalItems":false,"items":{"type":"string","description":"e.g. Friedrich Nietzsche"}}}}},"references":{"type":"array","description":"List references you have received","additionalItems":false,"items":{"type":"object","additionalProperties":true,"properties":{"name":{"type":"string","description":"e.g. Timothy Cook"},"reference":{"type":"string","description":"e.g. Joe blogs was a great employee, who turned up to work at least once a week. He exceeded my expectations when it came to doing nothing."}}}},"projects":{"type":"array","description":"Specify career projects","additionalItems":false,"items":{"type":"object","additionalProperties":true,"properties":{"name":{"type":"string","description":"e.g. The World Wide Web"},"description":{"type":"string","description":"Short summary of project. e.g. Collated works of 2017."},"highlights":{"type":"array","description":"Specify multiple features","additionalItems":false,"items":{"type":"string","description":"e.g. Directs you close but not quite there"}},"keywords":{"type":"array","description":"Specify special elements involved","additionalItems":false,"items":{"type":"string","description":"e.g. AngularJS"}},"startDate":{"$ref":"#/definitions/iso8601"},"endDate":{"$ref":"#/definitions/iso8601"},"url":{"type":"string","format":"uri","description":"e.g. http://www.computer.org/csdl/mags/co/1996/10/rx069-abs.html"},"roles":{"type":"array","description":"Specify your role on this project or in company","additionalItems":false,"items":{"type":"string","description":"e.g. Team Lead, Speaker, Writer"}},"entity":{"type":"string","description":"Specify the relevant company/entity affiliations e.g. 'greenpeace', 'corporationXYZ'"},"type":{"type":"string","description":" e.g. 'volunteering', 'presentation', 'talk', 'application', 'conference'"}}}},"meta":{"type":"object","description":"The schema version and any other tooling configuration lives here","additionalProperties":true,"properties":{"canonical":{"type":"string","description":"URL (as per RFC 3986) to latest version of this document","format":"uri"},"version":{"type":"string","description":"A version field which follows semver - e.g. v1.0.0"},"lastModified":{"type":"string","description":"Using ISO 8601 with YYYY-MM-DDThh:mm:ss"}}}},"title":"Resume Schema","type":"object"}

=== jonathan-hunter/jonathan-hunter.github.io/assets/json/resume.json
{"$schema":"http://json-schema.org/draft-07/schema#","basics":{"name":"Jonathan E. Hunter MChem Ph. D.","label":"Data Science | Chemical Informatics | Metabolomics | Analytical Chemistry | Life Sciences","email":"web-enq@hunter.phd","url":"https://hunter.phd","summary":"Driven to deliver impactful scientific insights through elegant solutions with a deep passion for life-long learning. Experienced in international, cross-disciplinary research with significant contributions in analytical chemistry and data science.","location":{"address":"","city":"Bristol","countryCode":"GB","region":"England"},"profiles":[{"network":"LinkedIn","username":"jonathan-hunter-a75540a3","url":"https://www.linkedin.com/in/jonathan-hunter-a75540a3"},{"network":"Google Scholar","username":"","url":"https://scholar.google.com/citations?user=qIGWQdwAAAAJ&hl=en&oi=sra"},{"network":"GitHub","username":"jonathan-hunter","url":"https://github.com/jonathan-hunter"},{"network":"Codewars","username":"Hntr1","url":"https://www.codewars.com/users/Hntr1"},{"network":"Kaggle","username":"jonathanehunter","url":"https://www.kaggle.com/jonathanehunter"},{"network":"DataCamp","username":"jonhunter","url":"https://www.datacamp.com/portfolio/jonhunter"}]},"work":[{"name":"EMBL-EBI","location":"Cambridge, UK","position":"Scientific Database Curator, Metabolomics","startDate":"2025-05","endDate":"Present","summary":"Bridging laboratory analytical chemistry through computational mass spectrometry to advance open data reuse and FAIR principles."},{"name":"LGC","location":"Cambridge, UK","description":"Led development of proprietary analytical methods for occupational drug testing utilising LC-MS and GC-MS approaches in a regulated laboratory environment. Also undertook contract research, implemented novel technologies and provided supervision, technical training and mentoring.","position":"Senior Scientist (Innovation)","startDate":"2019-02","endDate":"2023-01","summary":"Developed methods for phytocannabinoid determination and contributed key technical expertise to a large commercial research study on epicatechin metabolism.","highlights":["Developed proprietary analytical methods using LC-MS and GC-MS","Completed method validations for phytocannabinoids","Provided supervision and technical training"]},{"name":"Woods Hole Oceanographic Institution","location":"MA, USA","description":"Conducted research on microscale chemical and physical processes in marine organic matter degradation. Developed a novel nanoLC-MS methodology and collaborated with international partners.","position":"Postdoctoral Investigator","startDate":"2016-07","endDate":"2018-07","summary":"Implemented high-sensitivity nanoLC-MS techniques and delivered high impact publications including co-lead authorship in Science.","highlights":["Developed novel nanoLC-MS methodology for high-sensitivity analysis","Collaborated with partner laboratories in Zurich and Calgary","Delivered impactful publications in Science and Environmental Science & Technology"]},{"name":"University of Southampton, Faculty of Medicine","location":"Southampton, UK","description":"Characterized reactive oxygen and nitrogen modified lipids.","position":"Research Fellow","startDate":"2015-07","endDate":"2016-06","summary":"Conducted research on lipid modifications related to oxidative stress."},{"name":"AkzoNobel","location":"Deventer, Netherlands","description":"Synthesized metallocenes leading to a commercially successful large scale industrial production.","position":"Visiting Student","startDate":"2010-07","endDate":"2010-12","summary":"Developed and optimized a synthesis process for metallocenes."}],"education":[{"institution":"University of Southampton","area":"Phytoplankton Lipidomics: Lipid Dynamics in Response to Microalgal Stressors","studyType":"Doctor of Philosophy","startDate":"2011-08","endDate":"2015-07"},{"institution":"University of Southampton","area":"Master of Chemistry","startDate":"2007-10","endDate":"2011-07"}],"awards":[{"title":"Co-author of the Winning National Champion’s Research Article","date":"2025-04","awarder":"Frontiers Planet Prize "},{"title":"Spotlight Article","date":"2018-01","awarder":"Journal of Applied and Environmental Microbiology"},{"title":"Outstanding Student Presentation Award","date":"2015-02","awarder":"Aquatic Sciences Meeting, Granada, Spain"},{"title":"Vice Chancellor’s Scholarship Award","date":"2011-07","awarder":"University of Southampton"},{"title":"Bronze Award","date":"2009-11","awarder":"International Genetically Engineered Machines Competition, M.I.T."}],"certificates":[{"name":"Linux Commands & Shell Scripting Certification","date":"2024-10","url":"https://courses.edx.org/certificates/b44142cb8a714ab3ab8d590b0eba6a17","issuer":"IBM via EdX"},{"name":"Certified Cloud Practitioner Certification","date":"2024-06","url":"https://cp.certmetrics.com/amazon/en/public/verify/credential/adbe971b6d0e4f64ae251bc190e9f6d7","issuer":"AWS"},{"name":"Professional Data Scientist (Python) Certification","date":"2024-05","url":"https://www.datacamp.com/certificate/DS0025230650482","issuer":"DataCamp"},{"name":"Stepping up to Leadership Certification","date":"2022-05","issuer":"Bespoke Training and Development"},{"name":"Good Record Keeping and Data Integrity","date":"2019-04","issuer":"LGC"},{"name":"Multivariate Statistical and Topological Data Analysis Workshop","date":"2014-09","issuer":"University of Southampton"}],"publications":[{"name":"Microbial metabolic specificity controls pelagic lipid export efficiency","publisher":"Science & bioRxiv","releaseDate":"2024-01","url":"https://doi.org/10.1126/science.aab2661","summary":"Co-lead author publication discussing microbial metabolic specificity in pelagic lipid export efficiency."},{"name":"Using high-sensitivity lipidomics to assess microscale heterogeneity in oceanic sinking particles and single phytoplankton cells","publisher":"Environmental Science & Technology","releaseDate":"2021-01","url":"https://doi.org/10.1021/acs.est.1c02836","summary":"Study on the application of lipidomics in understanding microscale heterogeneity in oceanic particles."},{"name":"Coccolithovirus facilitation of carbon export in the North Atlantic","publisher":"Nature Microbiology","releaseDate":"2018-01","url":"https://doi.org/10.1038/s41564-018-0128-4","summary":"Research on the role of coccolithovirus in facilitating carbon export in the North Atlantic."},{"name":"Lipidomics of Thalassiosira pseudonana Under Phosphorus Stress Reveal Underlying Phospholipid Substitution Dynamics and Novel Diglycosylceramide Substitutes","publisher":"Applied and Environmental Microbiology","releaseDate":"2018-01","url":"https://doi.org/10.1128/AEM.02034-17","summary":"Investigation into phospholipid substitution dynamics in Thalassiosira pseudonana under phosphorus stress."},{"name":"Targeted and Untargeted Lipidomics of Emiliania huxleyi Viral Infection and Life Cycle Phases Highlights Molecular Biomarkers of Infection, Susceptibility, and Ploidy","publisher":"Frontiers in Marine Science","releaseDate":"2015-01","url":"https://doi.org/10.3389/fmars.2015.00081","summary":"Study highlighting molecular biomarkers related to viral infection in Emiliania huxleyi."}],"skills":[{"name":"Python","level":"Advanced","keywords":["Pandas","NumPy","SciPy","Scikit-learn","Matplotlib","Seaborn"]},{"name":"Scientific Analysis","level":"Advanced","keywords":["Bioanalysis","Experimental Design","Statistical Analysis","Data Visualisation"]},{"name":"Research & Collaboration","level":"Advanced","keywords":["Cross-Disciplinary Research","International Collaboration","Leadership","Mentorship","Project Management"]},{"name":"SQL","level":"Intermediate","keywords":["PostgreSQL"]},{"name":"Linux","level":"Intermediate","keywords":["Bash"]},{"name":"R","level":"Intermediate","keywords":["XCMS"]},{"name":"AWS","level":"Intermediate","keywords":["AWS CCP"]},{"name":"Git","level":"Intermediate","keywords":[]},{"name":"OpenAI API","level":"Intermediate","keywords":[]},{"name":"LC-MS Software","level":"Advanced","keywords":["Thermo Xcalibur","Waters Masslynx","Bruker Data Analysis"]},{"name":"MATLAB","level":"Basic","keywords":[]},{"name":"Tableau","level":"Basic","keywords":[]},{"name":"Docker","level":"Basic","keywords":[]},{"name":"GitHub/GitLab","level":"Basic","keywords":[]}],"languages":[{"language":"English","fluency":"Native"}],"interests":[{"name":"Personal Interests","keywords":["mountain biking","running","chess","reading","cooking","learning new skills","family"]}],"meta":{"canonical":"http://example.com/example.json","version":"v1.0.0","lastModified":"2025-02-18T00:00:00"}}
